"""Versioned schema ported from the verified offline PSI renderer."""

from typing import Any

# Static heterogeneous schema; values are checked by the payload boundary.
# pyright: reportAny=false, reportExplicitAny=false
SCHEMA: tuple[dict[str, Any], ...] = (
    {
        "name": "PSI Summary",
        "title": "PSI SUMMARY — 27.08.2026",
        "headers": ["Item", "Value", "Item", "Value"],
        "key": None,
        "widths": {0: 31, 1: 25, 2: 33, 3: 28},
        "quantity": [],
        "money": [],
        "percent": [],
    },
    {
        "name": "Checks",
        "title": "RELEASE CHECKS",
        "headers": ["Check", "Expected", "Actual", "Status", "Notes"],
        "key": None,
        "widths": {0: 30, 1: 37, 2: 26, 3: 13, 4: 70},
        "quantity": [],
        "money": [],
        "percent": [],
    },
    {
        "name": "Sources",
        "title": "SOURCES & LINEAGE",
        "headers": ["Source", "File", "Role / Rule", "SHA-256"],
        "key": None,
        "widths": {0: 26, 1: 58, 2: 48, 3: 66},
        "quantity": [],
        "money": [],
        "percent": [],
    },
    {
        "name": "Mismatch",
        "title": "MISMATCH",
        "headers": [
            "Status",
            "Source",
            "Key",
            "Issue",
            "Resolution",
            "Evidence",
            "New since prior PSI",
        ],
        "key": None,
        "widths": {0: 14, 1: 20, 2: 29, 3: 42, 4: 58, 5: 68, 6: 18},
        "quantity": [],
        "money": [],
        "percent": [],
    },
    {
        "name": "Data gaps",
        "title": "DATA GAPS",
        "headers": ["Source", "Key", "Issue", "Required action"],
        "key": None,
        "widths": {0: 20, 1: 31, 2: 48, 3: 66},
        "quantity": [],
        "money": [],
        "percent": [],
    },
    {
        "name": "PO excluded",
        "title": "PURCHASE ORDER EXCLUDED",
        "headers": ["No", "PRODUCT ID", "PRODUCT NAME", "Reason"],
        "key": "po_excluded_rows",
        "widths": {0: 10, 1: 22, 2: 65, 3: 60},
        "quantity": [],
        "money": [],
        "percent": [],
    },
    {
        "name": "PSI by Product",
        "title": "PSI BY PRODUCT",
        "headers": [
            "Mã hàng",
            "Tên hàng",
            "Brand",
            "Category",
            "Sub Category",
            "Code status",
            "SL bán thuần",
            "Doanh số thuần",
            "COGS",
            "Gross profit",
            "Gross margin",
            "SL tồn cuối kỳ",
            "GT tồn cuối kỳ",
            "SL Pre-order mở",
            "SL PO mở",
        ],
        "key": "psi_product_rows",
        "widths": {0: 21, 1: 64, 2: 22, 3: 22, 4: 22, 5: 18},
        "quantity": [6, 11, 13, 14],
        "money": [7, 8, 9, 12],
        "percent": [10],
    },
    {
        "name": "Brand",
        "title": "BRAND",
        "headers": ["Brand", "Brand Code"],
        "key": "brand_rows",
        "widths": {0: 32, 1: 20},
        "quantity": [],
        "money": [],
        "percent": [],
    },
    {
        "name": "Category",
        "title": "CATEGORY",
        "headers": ["Category", "Sub Category"],
        "key": "category_rows",
        "widths": {0: 30, 1: 34},
        "quantity": [],
        "money": [],
        "percent": [],
    },
    {
        "name": "Purchase",
        "title": "PURCHASE / PO",
        "headers": [
            "No",
            "Status",
            "Supplier",
            "PO",
            "Số ĐH",
            "Ngày PO",
            "Brand",
            "PRE-ORDER/STOCK",
            "PRODUCT ID",
            "PRODUCT NAME",
            "QUANTITY",
            "WAREHOUSE VALUE",
            "CURRENCY",
            "EXW VALUE",
            "ETA",
        ],
        "key": "purchase_rows",
        "widths": {0: 9, 3: 36, 4: 24, 5: 15, 8: 21, 9: 65, 14: 16},
        "quantity": [10],
        "money": [11, 13],
        "percent": [],
    },
    {
        "name": "Inventory",
        "title": "INVENTORY",
        "headers": [
            "NO",
            "DATA DATE",
            "PRODUCT ID",
            "PRODUCT NAME",
            "CATEGORIES",
            "SUBCATEGORIES",
            "SUPPLIER",
            "BRAND CODE",
            "QUANTITY",
            "VALUE",
            "WAREHOUSE",
        ],
        "key": "inventory_rows",
        "widths": {0: 10, 1: 15, 2: 21, 3: 65, 4: 22, 5: 22, 6: 24, 7: 19, 10: 22},
        "quantity": [8],
        "money": [9],
        "percent": [],
    },
    {
        "name": "Pre-orders",
        "title": "OPEN PRE-ORDERS",
        "headers": [
            "No",
            "SALES DATE",
            "PRODUCT ID",
            "PRODUCT NAME",
            "CATEGORIES",
            "SUBCATEGORIES",
            "SUPPLIER",
            "BRAND CODE",
            "QUANTITY SOLD",
            "NET REV SOLD",
            "COST TO WH BY PUR (Estimate)",
            "INVOICE NO.",
            "ĐH",
            "HẠN GIAO HÀNG",
            "Column1",
            "Map",
            "KT check",
            "Xử lý",
        ],
        "key": "preorder_rows",
        "widths": {0: 9, 1: 15, 2: 21, 3: 65, 12: 18, 13: 16, 16: 34, 17: 30},
        "quantity": [8],
        "money": [9, 10],
        "percent": [],
    },
    {
        "name": "Preorder excluded KT",
        "title": "PRE-ORDER EXCLUDED BY ACCOUNTING REVIEW",
        "headers": [
            "No",
            "SALES DATE",
            "PRODUCT ID",
            "PRODUCT NAME",
            "CATEGORIES",
            "SUBCATEGORIES",
            "SUPPLIER",
            "BRAND CODE",
            "QUANTITY SOLD",
            "NET REV SOLD",
            "COST TO WH BY PUR (Estimate)",
            "INVOICE NO.",
            "ĐH",
            "HẠN GIAO HÀNG",
            "Column1",
            "Map",
            "KT check",
            "Xử lý",
        ],
        "key": "preorder_excluded_rows",
        "widths": {0: 9, 1: 15, 2: 21, 3: 65, 12: 18, 13: 16, 16: 34, 17: 30},
        "quantity": [8],
        "money": [9, 10],
        "percent": [],
    },
    {
        "name": "Revenue",
        "title": "REVENUE",
        "headers": [
            "No.",
            "SALES DATE",
            "PRODUCT ID",
            "PRODUCT NAME",
            "CATEGORIES",
            "SUBCATEGORIES",
            "SUPPLIER",
            "BRAND CODE",
            "TOTAL QUANTITY SOLD",
            "NET REV SOLD",
            "COGS",
            "SALE ORDER",
            "SHOWROOM SOLD",
            "CHANEL",
            "Column1",
            "Số đúng trên file PSI cũ và báo cáo bán hàng",
            "Chênh lệch",
            "Note",
        ],
        "key": "revenue_rows",
        "widths": {0: 9, 1: 15, 2: 21, 3: 65, 8: 19, 9: 21, 10: 21, 11: 19, 17: 34},
        "quantity": [8],
        "money": [9, 10, 15, 16],
        "percent": [],
    },
    {
        "name": "CRM Final",
        "title": "CRM FINAL — APPROVAL DATE",
        "headers": [
            "Số đơn hàng",
            "Khách hàng",
            "Mã khách hàng",
            "Ngày duyệt",
            "Giá trị đơn hàng",
            "Giá trị đã xuất hóa đơn",
            "Tình trạng",
            "Trạng thái phê duyệt",
            "Tình trạng giao hàng",
            "Tình trạng thanh toán",
        ],
        "key": "crm_final_rows",
        "widths": {0: 18, 1: 46, 2: 18, 3: 15, 6: 20, 7: 20, 8: 22, 9: 22},
        "quantity": [],
        "money": [4, 5],
        "percent": [],
    },
    {
        "name": "Final CRM Products",
        "title": "FINAL CRM PRODUCTS — ORDERS IN CRM FINAL ONLY",
        "headers": [
            "Số đơn hàng",
            "PRODUCT ID",
            "PRODUCT NAME",
            "QUANTITY",
            "NET REV SOLD",
            "Ngày duyệt",
        ],
        "key": "crm_product_rows",
        "widths": {0: 18, 1: 21, 2: 65, 5: 15},
        "quantity": [3],
        "money": [4],
        "percent": [],
    },
    {
        "name": "Target",
        "title": "TARGET",
        "headers": None,
        "key": None,
        "widths": {0: 20, 1: 28, 2: 21, 3: 22, 4: 20, 5: 20, 6: 20, 7: 20, 8: 20},
        "quantity": [4],
        "money": [5, 6, 7, 8],
        "percent": [],
    },
)
