// NeonHost and NeonDatabase parameters required; no credentials in M.
let
    Source = PostgreSQL.Database(NeonHost, NeonDatabase, [CreateNavigationProperties=false]),
    Rows = Source{[Schema="psi_powerbi", Item="purchase"]}[Data],
    Selected = Table.SelectColumns(Rows, {"Tình trạng", "Số HĐ", "Số PO", "PO DATE", "STOCK-IN DATE", "PRODUCT ID", "QUANTITY", "PRICE ORDER", "TOTAL AMOUNT", "CURRENCY", "F.O.C", "WAREHOUSE VALUE/UNIT", "TOTAL WAREHOUSE VALUE", "Process Stage", "Loading No.", "SALES ORDER", "YEAR", "Tỷ giá", "Import tax", "Transport Mode", "ETD", "ETA", "Deposit", "Deposit Date", "Deposit status", "Payment", "Payment date", "Payment  status", "Balance", "Transport cost", "Transport cost status", "Serive cost", "Số Lô", "PRODUCT NAME"}),
    Typed = Table.TransformColumnTypes(Selected, {{"Tình trạng", type text}, {"Số HĐ", type text}, {"Số PO", type text}, {"PO DATE", type datetime}, {"STOCK-IN DATE", type datetime}, {"PRODUCT ID", type text}, {"QUANTITY", type number}, {"PRICE ORDER", type number}, {"TOTAL AMOUNT", type number}, {"CURRENCY", type text}, {"F.O.C", type text}, {"WAREHOUSE VALUE/UNIT", type number}, {"TOTAL WAREHOUSE VALUE", type number}, {"Process Stage", type text}, {"Loading No.", type text}, {"SALES ORDER", type text}, {"YEAR", Int64.Type}, {"Tỷ giá", type number}, {"Import tax", type number}, {"Transport Mode", type text}, {"ETD", type datetime}, {"ETA", type datetime}, {"Deposit", type number}, {"Deposit Date", type datetime}, {"Deposit status", type text}, {"Payment", type number}, {"Payment date", type datetime}, {"Payment  status", type text}, {"Balance", Int64.Type}, {"Transport cost", type number}, {"Transport cost status", type text}, {"Serive cost", type number}, {"Số Lô", type text}, {"PRODUCT NAME", type text}}, "en-US")
in
    Typed
