let
    Payload = GetPSIPayload(NeonHost, NeonDatabase, ReportId),
    Rows = Table.FromRows(Payload[purchase_rows], {"NO", "Tình trạng", "SUPPLIER", "Số PO", "SALES ORDER", "PO DATE", "BRAND NAME", "PRE-ORDER/STOCK", "PRODUCT ID", "PRODUCT NAME", "QUANTITY", "TOTAL WAREHOUSE VALUE", "CURRENCY", "EXW VALUE", "ETA"}),
    UnitWarehouse = Table.AddColumn(Rows, "WAREHOUSE VALUE/UNIT", each if [QUANTITY] = null or [QUANTITY] = 0 then null else [TOTAL WAREHOUSE VALUE] / [QUANTITY], type number),
    Missing = List.Accumulate({"Số HĐ", "STOCK-IN DATE", "PRICE ORDER", "TOTAL AMOUNT", "F.O.C", "Process Stage", "Loading No.", "Tỷ giá", "Import tax", "Transport Mode", "ETD", "Deposit", "Deposit Date", "Deposit status", "Payment", "Payment date", "Payment  status", "Balance", "Transport cost", "Transport cost status", "Serive cost", "Số Lô"}, UnitWarehouse, (state, column) => Table.AddColumn(state, column, each null)),
    Year = Table.AddColumn(Missing, "YEAR", each if [PO DATE] = null then null else Date.Year(Date.From([PO DATE])), Int64.Type),
    Selected = Table.SelectColumns(Year, {"Tình trạng", "Số HĐ", "Số PO", "PO DATE", "STOCK-IN DATE", "PRODUCT ID", "QUANTITY", "PRICE ORDER", "TOTAL AMOUNT", "CURRENCY", "F.O.C", "WAREHOUSE VALUE/UNIT", "TOTAL WAREHOUSE VALUE", "Process Stage", "Loading No.", "SALES ORDER", "YEAR", "Tỷ giá", "Import tax", "Transport Mode", "ETD", "ETA", "Deposit", "Deposit Date", "Deposit status", "Payment", "Payment date", "Payment  status", "Balance", "Transport cost", "Transport cost status", "Serive cost", "Số Lô", "PRODUCT NAME"}),
    Typed = Table.TransformColumnTypes(Selected, {{"Tình trạng", type text}, {"Số HĐ", type text}, {"Số PO", type text}, {"PO DATE", type date}, {"STOCK-IN DATE", type date}, {"PRODUCT ID", type text}, {"QUANTITY", type number}, {"PRICE ORDER", type number}, {"TOTAL AMOUNT", type number}, {"CURRENCY", type text}, {"F.O.C", type text}, {"WAREHOUSE VALUE/UNIT", type number}, {"TOTAL WAREHOUSE VALUE", type number}, {"Process Stage", type text}, {"Loading No.", type text}, {"SALES ORDER", type text}, {"YEAR", Int64.Type}, {"Tỷ giá", type number}, {"Import tax", type number}, {"Transport Mode", type text}, {"ETD", type date}, {"ETA", type date}, {"Deposit", type number}, {"Deposit Date", type date}, {"Deposit status", type text}, {"Payment", type number}, {"Payment date", type date}, {"Payment  status", type text}, {"Balance", Int64.Type}, {"Transport cost", type number}, {"Transport cost status", type text}, {"Serive cost", type number}, {"Số Lô", type text}, {"PRODUCT NAME", type text}}, "en-US")
in
    Typed
